### ISSUE TITLE
Data, safe for use?

### ISSUE THREAD

**Issue by a2** [zwaldowski/ParksAndRecreation#2]
[This comment](https://github.com/zwaldowski/ParksAndRecreation/blob/cc5fcb48a8b4a31d30e954f452bc5d2fb7e4f383/Data.playground/Sources/Data%2BNSData.swift#L50-L51) made me wonder whether the code in the Data playground is safe for production. Is it all kosher?

**Comment by zwaldowski** [comment]
That's a fair point. :relaxed:

I've seen implementations of `_ObjectiveCBridgeable` ship, and this one continues to work to this day in Beta 6. If there's any discomfort about it, I think it's wise to remove it if one adopt `Data`s in any of their own code.

It should probably expose a `.objectValue` instead, but magical bridging is just so convenient.

**Comment by zwaldowski** [comment]
This ends up being far cleaner anyway, at at least somewhat safer… at least until, god help us, Swift code is running without Foundation linked.

```swift

extension Data {
    
    /// Convert `self` to Objective-C.
    public var objectValue: NSData! {
        assert(OS_OBJECT_USE_OBJC != 0, "Casting `Data<T>` to `NSData` requires Objective-C ARC bridging for OS objects.")
        return data as? NSData
    }
    
}

```

**Comment by zwaldowski** [comment]
The release of the stdlib makes it clear `_ObjectiveCBridgeable` isn't meant to be implemented. Removed in 3c32a5f. `objectValue`, introduced in its place, is currently not suitable in an environment without ObjC Foundation, but that can be fixed later on.
